export const GET_BRANCHES = "GET_BRANCHES";
export const FAILED_TO_GET_BRANCHES = "FAILED_TO_GET_BRANCHES";

export const GET_SINGLE_BRANCH = "GET_SINGLE_BRANCH";
export const FAILED_TO_GET_SINGLE_BRANCH = "FAILED_TO_GET_SINGLE_BRANCH";
