export const POST_CATEGORY = "POST_CATEGORY";
export const FAILED_TO_POST_CATEGORY = "FAILED_TO_POST_CATEGORY";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const FAILED_TO_GET_CATEGORIES = "FAILED_TO_GET_CATEGORIES";

export const GET_CATEGORY = "GET_CATEGORY";
export const FAILED_TO_GET_CATEGORY = "FAILED_TO_GET_CATEGORY";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const FAILED_TO_UPDATE_CATEGORY = "FAILED_TO_UPDATE_CATEGORY";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const FAILED_TO_DELETE_CATEGORY = "FAILED_TO_DELETE_CATEGORY";
