export const GET_PRODUCT_ALLOCATIONS = "GET_PRODUCT_ALLOCATIONS";
export const FAILED_TO_GET_PRODUCT_ALLOCATIONS = "FAILED_TO_GET_PRODUCT_ALLOCATIONS";

export const GET_SINGLE_PRODUCT_ALLOCATION = "GET_SINGLE_PRODUCT_ALLOCATION";
export const FAILED_TO_GET_SINGLE_PRODUCT_ALLOCATION = "FAILED_TO_GET_SINGLE_PRODUCT_ALLOCATION";
