export const GET_SCHEDULES = "GET_SCHEDULES";
export const FAILED_TO_GET_SCHEDULES = "FAILED_TO_GET_SCHEDULES";

export const GET_SINGLE_SCHEDULE = "GET_SINGLE_SCHEDULE";
export const FAILED_TO_GET_SINGLE_SCHEDULE = "FAILED_TO_GET_SINGLE_SCHEDULE";

export const POST_SCHEDULE = "POST_SCHEDULE";
export const FAILED_TO_POST_SCHEDULE = "FAILED_TO_POST_SCHEDULE";

export const DELETE_SCHEDULE = "DELETE_SCHEDULE";
export const FAILED_TO_DELETE_SCHEDULE = "FAILED_TO_DELETE_SCHEDULE";

export const UPDATE_SCHEDULE = "UPDATE_SCHEDULE";
export const FAILED_TO_UPDATE_SCHEDULE = "FAILED_TO_UPDATE_SCHEDULE";
