export const POST_SERVICE = "POST_SERVICE";
export const FAILED_TO_POST_SERVICE = "FAILED_TO_POST_SERVICE";

export const GET_SERVICES = "GET_SERVICES";
export const FAILED_TO_GET_SERVICES = "FAILED_TO_GET_SERVICES";

export const GET_SERVICE = "GET_SERVICE";
export const FAILED_TO_GET_SERVICE = "FAILED_TO_GET_SERVICE";

export const UPDATE_SERVICE = "UPDATE_SERVICE";
export const FAILED_TO_UPDATE_SERVICE = "FAILED_TO_UPDATE_SERVICE";

export const DELETE_SERVICE = "DELETE_SERVICE";
export const FAILED_TO_DELETE_SERVICE = "FAILED_TO_DELETE_SERVICE";

export const GET_SERVICE_BY_CATEGORY = "GET_SERVICE_BY_CATEGORY";
export const FAILED_TO_GET_SERVICE_BY_CATEGORY = "FAILED_TO_GET_SERVICE_BY_CATEGORY";
