export const GET_ORDERS = "GET_ORDERS";
export const FAILED_TO_GET_ORDERS = "FAILED_TO_GET_ORDERS";

export const GET_SINGLE_ORDER = "GET_SINGLE_ORDER";
export const FAILED_TO_GET_SINGLE_ORDER = "FAILED_TO_GET_SINGLE_ORDER";

export const GET_ORDERS_NURSE = "GET_ORDERS_NURSE";
export const FAILED_TO_GET_ORDERS_NURSE = "FAILED_TO_GET_ORDERS_NURSE";

export const GET_ORDERS_BY_USER = "GET_ORDERS_BY_USER";
export const FAILED_TO_GET_ORDERS_BY_USER = "FAILED_TO_GET_ORDERS_BY_USER";

export const POST_ORDER = "POST_ORDER";
export const FAILED_TO_POST_ORDER = "FAILED_TO_POST_ORDER";

export const CANCEL_ORDER = "CANCEL_ORDER";
export const FAILED_TO_CANCEL_ORDER = "FAILED_TO_CANCEL_ORDER";

export const UPDATE_ORDER = "UPDATE_ORDER";
export const FAILED_TO_UPDATE_ORDER = "FAILED_TO_UPDATE_ORDER";
